extern "C" {
#define RRES_SUPPORT_COMPRESSION_LZ4
#define RRES_SUPPORT_ENCRYPTION_AES
#define RRES_SUPPORT_ENCRYPTION_XCHACHA20

#define RRES_IMPLEMENTATION
#include "rres.h"
#undef RRES_IMPLEMENTATION
#define RRES_RAYLIB_IMPLEMENTATION
#include "raylib.h"
#include "rres-raylib.h"
#undef RRES_RAYLIB_IMPLEMENTATION
}