/*******************************************************************************************
*
*   raylib [textures] example - raw data
*
*   Example complexity rating: [★★★☆] 3/4
*
*   NOTE: Images are loaded in CPU memory (RAM); textures are loaded in GPU memory (VRAM)
*
*   Example originally created with raylib 1.3, last time updated with raylib 3.5
*
*   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
*   BSD-like license that allows static linking with closed source software
*
*   Copyright (c) 2015-2025 Ramon Santamaria (@raysan5)
*
********************************************************************************************/

use raylib::prelude::*;
use raylib_showcase::SourceViewer;

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
fn main() {
    // Initialization
    //--------------------------------------------------------------------------------------
    let screen_width = 800;
    let screen_height = 450;

    let (mut rl, thread) = raylib::init()
        .size(screen_width, screen_height)
        .title("raylib [textures] example - raw data")
        .build();

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

    // Load RAW image data (512x512, 32bit RGBA, no file header)
    let fudesumi_raw = Image::load_image_raw(
        "resources/textures/fudesumi.raw",
        384,
        512,
        PixelFormat::PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 as i32,
        0,
    )
    .unwrap();
    let fudesumi = rl.load_texture_from_image(&thread, &fudesumi_raw).unwrap(); // Upload CPU (RAM) image to GPU (VRAM)
    drop(fudesumi_raw); // Unload CPU (RAM) image data

    // Generate a checked texture by code
    let im_width: i32 = 960;
    let im_height: i32 = 480;

    // Dynamic memory allocation to store pixels data (Color type) is replaced here by
    // an Image built via GenImageColor + draw_pixel — RAII via Image's Drop replaces
    // the raylib MemAlloc/UnloadImage pair in the C source.
    // SAFETY: GenImageColor returns an owned Image whose buffer raylib frees via
    // UnloadImage; Image::from_raw ties that to Drop. Image::gen_image_color wraps the
    // same call but is gated behind SUPPORT_IMAGE_GENERATION, which isn't propagated
    // through the showcase crate.
    let mut checked_im =
        unsafe { Image::from_raw(ffi::GenImageColor(im_width, im_height, Color::BLACK.into())) };

    for y in 0..im_height {
        for x in 0..im_width {
            if ((x / 32 + y / 32) / 1) % 2 == 0 {
                checked_im.draw_pixel(x, y, Color::ORANGE);
            } else {
                checked_im.draw_pixel(x, y, Color::GOLD);
            }
        }
    }

    // Load pixels data into an image structure and create texture
    // NOTE: We can assign pixels directly to data because Color is R8G8B8A8
    // data structure defining that pixelformat, format must be set properly
    let checked = rl.load_texture_from_image(&thread, &checked_im).unwrap();
    drop(checked_im); // Unload CPU (RAM) image data (pixels)

    rl.set_target_fps(60); // Set our game to run at 60 frames-per-second
    let mut viewer = SourceViewer::for_current_example();
    //---------------------------------------------------------------------------------------

    // Main game loop
    while !rl.window_should_close()
    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        viewer.update(&mut rl, &thread);
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        let mut d = rl.begin_drawing(&thread);

        d.clear_background(Color::RAYWHITE);

        d.draw_texture(
            &checked,
            screen_width / 2 - checked.width() / 2,
            screen_height / 2 - checked.height() / 2,
            Color::WHITE.alpha(0.5),
        );
        d.draw_texture(&fudesumi, 430, -30, Color::WHITE);

        d.draw_text("CHECKED TEXTURE ", 84, 85, 30, Color::BROWN);
        d.draw_text("GENERATED by CODE", 72, 148, 30, Color::BROWN);
        d.draw_text("and RAW IMAGE LOADING", 46, 210, 30, Color::BROWN);

        d.draw_text(
            "(c) Fudesumi sprite by Eiden Marsal",
            310,
            screen_height - 20,
            10,
            Color::BROWN,
        );

        viewer.draw(&mut d);
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    // UnloadTexture for `fudesumi`/`checked` handled by RAII drops.
    // CloseWindow() is handled by RAII drop of `rl`.
    //--------------------------------------------------------------------------------------
}
